# Generated by Django 5.1.2 on 2024-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=100)),
                ('masa', models.CharField(max_length=100)),
                ('czystosc', models.CharField(max_length=100)),
                ('barwa', models.CharField(max_length=100)),
                ('pochodzenie', models.CharField(max_length=100)),
                ('wlasciciel', models.CharField(max_length=100)),
            ],
        ),
    ]
