# Generated by Django 5.1.2 on 2024-10-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oko',
            new_name='DataCris',
        ),
    ]
